apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
  namespace: loadgenerator
spec:
  selector:
    matchLabels:
      app: loadgenerator
  template: 
    spec: 
      containers:
      - name: loadgenerator
        image: gcr.io/mean-krm-ff/cymbal-bank/release/loadgenerator:2c19bd1
        env:
        - name: LOG_LEVEL
          value: "info"